create database livraria;
use livraria;
create table livros(
id_livros int not null auto_increment,
título varchar(255),
autor varchar(255),
volume varchar(255), 
categoria varchar(255),
preço decimal (9,2),
primary key (id_livros)
);
create table hardware(
id_hardware int not null auto_increment,
marca varchar(255),
tipo text,
valor_hardware decimal (5,2),
primary key (id_hardware)
);
insert into livros
(título, autor, volume, categoria, preço)
values
("O conto da aia", "Margaret Atwood", "1", "Romance", "30.00"),
("Mirai Nikki", "Sakae Esuno", "1", "Mistério", "40.00"),
("Mirai Nikki", "Sakae Esuno", "2", "Mistério", "20.00"),
("Mirai Nikki", "Sakae Esuno", "3", "Mistério", "60.00"),
("Mirai Nikki", "Sakae Esuno", "4", "Mistério", "40.00"),
("Mirai Nikki", "Sakae Esuno", "5", "Mistério", "15.65"),
("Mirai Nikki", "Sakae Esuno", "6", "Mistério", "10.00"),
("Mirai Nikki", "Sakae Esuno", "7", "Mistério", "13.50"),
("Mirai Nikki", "Sakae Esuno", "8", "Mistério", "10.00"),
("Mirai Nikki", "Sakae Esuno", "9", "Mistério", "35.00"),
("Mirai Nikki", "Sakae Esuno", "10", "Mistério", "10.00"),
("Mirai Nikki", "Sakae Esuno", "11", "Mistério", "16.88"),
("Mirai Nikki", "Sakae Esuno", "12", "Mistério", "10.00");
insert into livros
(título, autor, volume, categoria, preço)
values
("Lobo", "Keith Giffen & Alan Grant", "1", "hq", "117.27"),
("O Máskara", "John Arcudi, Rodrigo Guerrino, Doug Mahnke", "1", "hq", "67.90"),
("V for Vendetta", "Alan Moore e David Lloyd", "1", "hq", "81.06"),
("Dragon Ball Super", "Akira Toriyama", "1", "Shounen", "21.90"),
("Dragon Ball Super", "Akira Toriyama", "2", "Shounen", "21.90"),
("Dragon Ball Super", "Akira Toriyama", "3", "Shounen", "21.90"),
("Dragon Ball Super", "Akira Toriyama", "4", "Shounen", "21.90");
insert into livros
(título, autor, volume, categoria, preço)
values
("Dragon Ball Super", "Akira Toriyama", "5", "Shounen", "21.90"),
("Dragon Ball Super", "Akira Toriyama", "6", "Shounen", "21.90"),
("Dragon Ball Super", "Akira Toriyama", "7", "Shounen", "21.90"),
("Dragon Ball Super", "Akira Toriyama", "8", "Shounen", "21.90"),
("Dragon Ball Super", "Akira Toriyama", "9", "Shounen", "21.90"),
("Dragon Ball Super", "Akira Toriyama", "10", "Shounen", "22.90"),
("Dragon Ball Super", "Akira Toriyama", "11", "Shounen", "22.90"),
("Dragon Ball Super", "Akira Toriyama", "12", "Shounen", "22.90"),
("Fire Force", "Atsushi Ohkubo", "1", "Shounen", "21.90"),
("Fire Force", "Atsushi Ohkubo", "2", "Shounen", "21.90"),
("Fire Force", "Atsushi Ohkubo", "3", "Shounen", "21.90"),
("Fire Force", "Atsushi Ohkubo", "4", "Shounen", "21.90");
insert into livros
(título, autor, volume, categoria, preço)
values
("Fire Force", "Atsushi Ohkubo", "5", "Shounen", "21.90"),
("Fire Force", "Atsushi Ohkubo", "6", "Shounen", "21.90"),
("Fire Force", "Atsushi Ohkubo", "7", "Shounen", "21.90"),
("Fire Force", "Atsushi Ohkubo", "8", "Shounen", "21.90"),
("Fire Force", "Atsushi Ohkubo", "9", "Shounen", "21.90"),
("Fire Force", "Atsushi Ohkubo", "10", "Shounen", "21.90"),
("Fire Force", "Atsushi Ohkubo", "11", "Shounen", "21.90"),
("Fire Force", "Atsushi Ohkubo", "12", "Shounen", "21.90"),
("Naruto", "Masashi Kishimoto", "1", "Shounen", "94.60"),
("Naruto", "Masashi Kishimoto", "2", "Shounen", "39.90");

insert into livros
(título, autor, volume, categoria, preço)
values
("Naruto", "Masashi Kishimoto", "3", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "4", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "5", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "6", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "7", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "8", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "9", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "10", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "11", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "12", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "13", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "14", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "15", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "16", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "17", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "18", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "19", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "20", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "21", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "22", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "23", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "24", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "25", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "26", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "27", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "28", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "29", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "30", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "31", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "32", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "33", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "34", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "35", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "36", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "37", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "38", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "39", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "40", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "41", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "42", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "43", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "44", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "45", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "46", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "47", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "48", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "49", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "50", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "51", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "52", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "53", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "54", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "55", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "56", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "57", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "58", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "59", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "60", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "61", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "62", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "63", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "64", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "65", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "66", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "67", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "68", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "69", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "70", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "71", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "72", "Shounen", "39.90"),
("Naruto", "Masashi Kishimoto", "73", "Shounen", "39.90");
insert into livros
(título, autor, volume, categoria, preço)
values
("Slam Dunk", "Takehiko Inoue", "1", "Shounen de Esporte", "19.90"),
("Slam Dunk", "Takehiko Inoue", "2", "Shounen de Esporte", "38.90"),
("Slam Dunk", "Takehiko Inoue", "3", "Shounen de Esporte", "11.70"),
("Slam Dunk", "Takehiko Inoue", "4", "Shounen de Esporte", "17.90"),
("Slam Dunk", "Takehiko Inoue", "5", "Shounen de Esporte", "33.90"),
("Slam Dunk", "Takehiko Inoue", "6", "Shounen de Esporte", "35.00"),
("Slam Dunk", "Takehiko Inoue", "7", "Shounen de Esporte", "33.00"),
("Slam Dunk", "Takehiko Inoue", "8", "Shounen de Esporte", "17.90"),
("Slam Dunk", "Takehiko Inoue", "9", "Shounen de Esporte", "14.90"),
("Slam Dunk", "Takehiko Inoue", "10", "Shounen de Esporte", "17.90");
insert into livros
(título, autor, volume, categoria, preço)
values
("Slam Dunk", "Takehiko Inoue", "11", "Shounen de Esporte", "14.32");
insert into livros
(título, autor, volume, categoria, preço)
values
("Slam Dunk", "Takehiko Inoue", "12", "Shounen de Esporte", "9.90");
insert into livros
(título, autor, volume, categoria, preço)
values
("Slam Dunk", "Takehiko Inoue", "13", "Shounen de Esporte", "39.00"),
("Slam Dunk", "Takehiko Inoue", "14", "Shounen de Esporte", "20.90"),
("Slam Dunk", "Takehiko Inoue", "15", "Shounen de Esporte", "20.90"),
("Slam Dunk", "Takehiko Inoue", "16", "Shounen de Esporte", "11.79");
insert into livros
(título, autor, volume, categoria, preço)
values
("Slam Dunk", "Takehiko Inoue", "17", "Shounen de Esporte", "16.72"),
("Slam Dunk", "Takehiko Inoue", "18", "Shounen de Esporte", "20.90"),
("Slam Dunk", "Takehiko Inoue", "19", "Shounen de Esporte", "35.00"),
("Slam Dunk", "Takehiko Inoue", "20", "Shounen de Esporte", "20.90"),
("Slam Dunk", "Takehiko Inoue", "21", "Shounen de Esporte", "38.90"),
("Slam Dunk", "Takehiko Inoue", "22", "Shounen de Esporte", "20.90"),
("Slam Dunk", "Takehiko Inoue", "23", "Shounen de Esporte", "20.90"),
("Slam Dunk", "Takehiko Inoue", "24", "Shounen de Esporte", "20.90");
insert into livros
(título, autor, volume, categoria, preço)
values
("Vigilante My Hero Academia Illegals", "Hideyuki Furuhashi", "1", "Shounen", "23.90"),
("Vigilante My Hero Academia Illegals", "Hideyuki Furuhashi", "2", "Shounen", "23.90"),
("Vigilante My Hero Academia", "Hideyuki Furuhashi", "1", "Shounen", "23.90"),
("Vigilante My Hero Academia", "Hideyuki Furuhashi", "2", "Shounen", "52.59"),
("Vigilante My Hero Academia", "Hideyuki Furuhashi", "3", "Shounen", "46.87"),
("Vigilante My Hero Academia", "Hideyuki Furuhashi", "4", "Shounen", "44.10"),
("Vigilante My Hero Academia", "Hideyuki Furuhashi", "5", "Shounen", "31.82"),
("Vigilante My Hero Academia", "Hideyuki Furuhashi", "6", "Shounen", "41.65"),
("Vigilante My Hero Academia", "Hideyuki Furuhashi", "7", "Shounen", "128.00"),
("Vigilante My Hero Academia", "Hideyuki Furuhashi", "8", "Shounen", "58.43");
insert into livros
(título, autor, volume, categoria, preço)
values
("Kuroko no Basket", "Tadatoshi Fujimaki", "1", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "2", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "3", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "4", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "5", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "6", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "7", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "8", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "9", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "10", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "11", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "12", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "13", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "14", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "15", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "16", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "17", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "18", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "18", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "19", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "20", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "21", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "22", "Shounen de Esporte", "11.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "23", "Shounen de Esporte", "10.00"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "24", "Shounen de Esporte", "15.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "25", "Shounen de Esporte", "13.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "26", "Shounen de Esporte", "13.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "27", "Shounen de Esporte", "39.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "28", "Shounen de Esporte", "13.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "29", "Shounen de Esporte", "13.90"),
("Kuroko no Basket", "Tadatoshi Fujimaki", "30", "Shounen de Esporte", "25.90");
insert into livros
(título, autor, volume, categoria, preço)
values
("Pokemon Ruby And Sapphire", "Satoshi Yamamoto", "1", "Shonen", "19.90"),
("Pokemon Ruby And Sapphire", "Satoshi Yamamoto", "2", "Shonen", "19.90"),
("Pokemon Ruby And Sapphire", "Satoshi Yamamoto", "3", "Shonen", "19.90"),
("Pokemon Ruby And Sapphire", "Satoshi Yamamoto", "4", "Shonen", "19.90"),
("Pokemon Ruby And Sapphire", "Satoshi Yamamoto", "5", "Shonen", "19.90"),
("Pokemon Ruby And Sapphire", "Satoshi Yamamoto", "6", "Shonen", "19.90"),
("Pokemon Ruby And Sapphire", "Satoshi Yamamoto", "7", "Shonen", "19.90"),
("Pokemon Ruby And Sapphire", "Satoshi Yamamoto", "8", "Shonen", "19.90");
insert into livros
(título, autor, volume, categoria, preço)
values
("Dr Slump", "AKira Toriyama", "1", "Comédia", "23.90"),
("Dr Slump", "AKira Toriyama", "2", "Comédia", "13.90"),
("Dr Slump", "AKira Toriyama", "3", "Comédia", "13.90"),
("Dr Slump", "AKira Toriyama", "4", "Comédia", "13.90"),
("Dr Slump", "AKira Toriyama", "5", "Comédia", "13.90"),
("Dr Slump", "AKira Toriyama", "6", "Comédia", "13.90"),
("Dr Slump", "AKira Toriyama", "7", "Comédia", "13.90"),
("Dr Slump", "AKira Toriyama", "8", "Comédia", "13.90"),
("Dr Slump", "AKira Toriyama", "9", "Comédia", "9.50"),
("Dr Slump", "AKira Toriyama", "10", "Comédia", "15.90"),
("Dr Slump", "AKira Toriyama", "11", "Comédia", "15.90"),
("Dr Slump", "AKira Toriyama", "12", "Comédia", "15.90"),
("Dr Slump", "AKira Toriyama", "13", "Comédia", "15.90"),
("Dr Slump", "AKira Toriyama", "14", "Comédia", "15.90"),
("Dr Slump", "AKira Toriyama", "15", "Comédia", "15.90"),
("Dr Slump", "AKira Toriyama", "16", "Comédia", "15.90"),
("Dr Slump", "AKira Toriyama", "17", "Comédia", "15.90"),
("Dr Slump", "AKira Toriyama", "18", "Comédia", "69.90"),
("Berserk", "Kentaro Miura", "1", "Fantasia sombria", "79.92"),
("Berserk", "Kentaro Miura", "2", "Fantasia sombria", "80.87"),
("Berserk", "Kentaro Miura", "3", "Fantasia sombria", "70.99"),
("Berserk", "Kentaro Miura", "4", "Fantasia sombria", "86.94"),
("Berserk", "Kentaro Miura", "5", "Fantasia sombria", "86.94"),
("Berserk", "Kentaro Miura", "6", "Fantasia sombria", "84.18"),
("Berserk", "Kentaro Miura", "7", "Fantasia sombria", "83.62"),
("Berserk", "Kentaro Miura", "8", "Fantasia sombria", "88.64"),
("Berserk", "Kentaro Miura", "9", "Fantasia sombria", "82.35"),
("Berserk", "Kentaro Miura", "10", "Fantasia sombria", "60.48"),
("Berserk", "Kentaro Miura", "11", "Fantasia sombria", "46.00"),
("Berserk", "Kentaro Miura", "12", "Fantasia sombria", "83.70"),
("Berserk", "Kentaro Miura", "13", "Fantasia sombria", "76.00"),
("Berserk", "Kentaro Miura", "14", "Fantasia sombria", "88.84"),
("Berserk", "Kentaro Miura", "15", "Fantasia sombria", "58.85"),
("Berserk", "Kentaro Miura", "16", "Fantasia sombria", "43.24"),
("Berserk", "Kentaro Miura", "17", "Fantasia sombria", "74.44"),
("Berserk", "Kentaro Miura", "18", "Fantasia sombria", "84.16"),
("Berserk", "Kentaro Miura", "19", "Fantasia sombria", "88.64"),
("Berserk", "Kentaro Miura", "20", "Fantasia sombria", "39.89"),
("Berserk", "Kentaro Miura", "21", "Fantasia sombria", "25.00"),
("Berserk", "Kentaro Miura", "22", "Fantasia sombria", "85.61"),
("Berserk", "Kentaro Miura", "23", "Fantasia sombria", "83.94"),
("Berserk", "Kentaro Miura", "24", "Fantasia sombria", "55.00"),
("Berserk", "Kentaro Miura", "25", "Fantasia sombria", "13.90"),
("Berserk", "Kentaro Miura", "26", "Fantasia sombria", "82.35"),
("Berserk", "Kentaro Miura", "27", "Fantasia sombria", "30.90"),
("Berserk", "Kentaro Miura", "28", "Fantasia sombria", "16.90"),
("Berserk", "Kentaro Miura", "29", "Fantasia sombria", "17.00"),
("Berserk", "Kentaro Miura", "30", "Fantasia sombria", "10.20"),
("Berserk", "Kentaro Miura", "31", "Fantasia sombria", "87.18"),
("Berserk", "Kentaro Miura", "32", "Fantasia sombria", "21.90"),
("Berserk", "Kentaro Miura", "33", "Fantasia sombria", "26.90"),
("Berserk", "Kentaro Miura", "34", "Fantasia sombria", "40.00"),
("Berserk", "Kentaro Miura", "35", "Fantasia sombria", "83.94"),
("Berserk", "Kentaro Miura", "36", "Fantasia sombria", "87.42"),
("Berserk", "Kentaro Miura", "37", "Fantasia sombria", "21.10"),
("Berserk", "Kentaro Miura", "38", "Fantasia sombria", "24.90");
insert into livros
(título, autor, volume, categoria, preço)
values
("Ranma 1/2", "Rumiko Takahashi", "1", "Comédia", "136.10"),
("Ranma 1/2", "Rumiko Takahashi", "2", "Comédia", "22.00"),
("Ranma 1/2", "Rumiko Takahashi", "3", "Comédia", "22.00"),
("Ranma 1/2", "Rumiko Takahashi", "4", "Comédia", "90.26"),
("Ranma 1/2", "Rumiko Takahashi", "5", "Comédia", "81.44"),
("Ranma 1/2", "Rumiko Takahashi", "6", "Comédia", "134.89"),
("Ranma 1/2", "Rumiko Takahashi", "7", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "8", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "9", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "10", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "11", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "12", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "13", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "14", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "15", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "16", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "17", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "18", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "19", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "20", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "21", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "22", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "23", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "24", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "25", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "26", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "27", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "28", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "29", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "30", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "31", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "32", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "33", "Comédia", ""),
("Ranma 1/2", "Rumiko Takahashi", "34", "Comédia", "");
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", ""),
("", "", "", "", "");
SELECT SUM(preço) AS total 
FROM livros;
drop database livraria;