create database hqs;
use hqs;
create table hqs(
id_hqs int not null auto_increment,
titulo text,
edição int,
lido boolean,
primary key(id_hqs)
);
create table Filmes(
id_Filmes int not null auto_increment,
titulo text,
diretor text,
Gênero text,
Ano int,
primary key(id_Filmes)
);
insert into hqs
(titulo, edição, lido)
values
("A queda do morcego", "1", "0"),
("A queda do morcego", "2", "0"),
("A queda do morcego", "3", "0"),
("A queda do morcego", "4", "0"),
("A queda do morcego", "5", "0"),
("A queda do morcego", "6", "0"),
("A queda do morcego", "7", "0"),
("A queda do morcego", "8", "0"),
("A queda do morcego", "9", "0"),
("A queda do morcego", "10", "0"),
("A queda do morcego", "11", "0"),
("A queda do morcego", "12", "0"),
("A queda do morcego", "13", "0"),
("A queda do morcego", "14", "0"),
("A queda do morcego", "15", "0"),
("A queda do morcego", "16", "0"),
("A queda do morcego", "17", "0"),
("A queda do morcego", "18", "0"),
("A queda do morcego", "19", "0"),
("A queda do morcego", "20", "0"),
("A queda do morcego", "21", "0"),
("A queda do morcego", "22", "0"),
("A queda do morcego", "23", "0"),
("A queda do morcego", "24", "0"),
("A queda do morcego", "25", "0"),
("A queda do morcego", "26", "0"),
("A queda do morcego", "27", "0"),
("A queda do morcego", "28", "0"),
("A queda do morcego", "29", "0"),
("A queda do morcego", "30", "0"),
("A queda do morcego", "31", "0"),
("A queda do morcego", "32", "0"),
("A queda do morcego", "33", "0"),
("A queda do morcego", "34", "0"),
("A queda do morcego", "35", "0"),
("A queda do morcego", "36", "0"),
("A queda do morcego", "37", "0"),
("A queda do morcego", "38", "0"),
("A queda do morcego", "39", "0"),
("A queda do morcego", "40", "0"),
("A queda do morcego", "41", "0"),
("A queda do morcego", "42", "0"),
("A queda do morcego", "43", "0"),
("A queda do morcego", "44", "0"),
("A queda do morcego", "45", "0"),
("A queda do morcego", "46", "0"),
("A queda do morcego", "47", "0"),
("A queda do morcego", "48", "0"),
("A queda do morcego", "49", "0"),
("A queda do morcego", "50", "0"),
("A queda do morcego", "51", "0"),
("A queda do morcego", "52", "0"),
("A queda do morcego", "53", "0"),
("A queda do morcego", "54", "0"),
("A queda do morcego", "55", "0"),
("A queda do morcego", "56", "0"),
("A queda do morcego", "57", "0"),
("A queda do morcego", "58", "0"),
("A queda do morcego", "59", "0"),
("A queda do morcego", "60", "0"),
("A queda do morcego", "61", "0"),
("A queda do morcego", "62", "0"),
("A queda do morcego", "63", "0"),
("A queda do morcego", "64", "0"),
("A queda do morcego", "65", "0"),
("A queda do morcego", "66", "0"),
("A queda do morcego", "67", "0"),
("A queda do morcego", "68", "0"),
("A queda do morcego", "69", "0"),
("A queda do morcego", "70", "0"),
("A queda do morcego", "71", "0"),
("A queda do morcego", "72", "0"),
("A queda do morcego", "73", "0"),
("A queda do morcego", "74", "0"),
("A queda do morcego", "75", "0"),
("A queda do morcego", "76", "0"),
("A queda do morcego", "77", "0"),
("A queda do morcego", "78", "0"),
("A queda do morcego", "79", "0"),
("A queda do morcego", "80", "0"),
("A queda do morcego", "81", "0"),
("A queda do morcego", "82", "0"),
("A queda do morcego", "83", "0"),
("A queda do morcego", "84", "0"),
("A queda do morcego", "85", "0"),
("A queda do morcego", "86", "0"),
("A queda do morcego", "87", "0"),
("A queda do morcego", "88", "0"),
("A queda do morcego", "89", "0"),
("A queda do morcego", "90", "0"),
("A queda do morcego", "91", "0"),
("A queda do morcego", "92", "0"),
("A queda do morcego", "93", "0"),
("A queda do morcego", "94", "0"),
("A queda do morcego", "95", "0"),
("A queda do morcego", "96", "0"),
("A queda do morcego", "97", "0"),
("A queda do morcego", "98", "0"),
("A queda do morcego", "99", "0"),
("A queda do morcego", "100", "0"),
("A queda do morcego", "101", "0"),
("A queda do morcego", "102", "0"),
("A queda do morcego", "103", "0"),
("A queda do morcego", "104", "0"),
("A queda do morcego", "105", "0"),
("A queda do morcego", "106", "0"),
("A queda do morcego", "107", "0"),
("A queda do morcego", "108", "0"),
("A queda do morcego", "109", "0"),
("A queda do morcego", "110", "0"),
("A queda do morcego", "111", "0"),
("A queda do morcego", "112", "0"),
("A queda do morcego", "113", "0"),
("A queda do morcego", "114", "0"),
("Injustiça marco zero", "1", "0"),
("Injustiça marco zero", "2", "0"),
("Injustiça marco zero", "3", "0"),
("Injustiça marco zero", "4", "0"),
("Injustiça marco zero", "5", "0"),
("Injustiça marco zero", "6", "0"),
("Injustiça marco zero", "7", "0"),
("Flash", "1", "0"),
("Flash", "2", "0"),
("Flash", "3", "0"),
("Flash", "4", "0"),
("Flash", "5", "0"),
("Flash", "6", "0"),
("Flash", "7", "0"),
("Flash", "8", "0"),
("Flash", "9", "0"),
("Flash", "10", "0"),
("Flash", "11", "0"),
("Flash", "12", "0"),
("Flash", "13", "0"),
("Flash", "14", "0"),
("Flash", "15", "0"),
("Flash", "16", "0"),
("Flash", "17", "0"),
("Flash", "18", "0"),
("Flash", "19", "0"),
("Flash", "20", "0"),
("Mulher gato Anual", "1", "1"),
("Mulher gato", "1", "1"),
("Mulher gato", "2", "0"),
("Mulher gato", "3", "0"),
("Mulher gato", "4", "0"),
("Mulher gato", "5", "0"),
("Mulher gato", "6", "0"),
("Mulher gato", "7", "0"),
("Mulher gato", "8", "0"),
("Mulher gato", "9", "0"),
("Mulher gato", "10", "0"),
("Mulher gato", "11", "0"),
("Mulher gato", "12", "0"),
("Mulher gato", "13", "0"),
("Mulher gato", "14", "0"),
("Mulher gato", "15", "0"),
("Mulher gato", "16", "0"),
("Mulher gato", "17", "0"),
("Mulher gato", "18", "0"),
("Mulher gato", "19", "0"),
("Mulher gato", "20", "0"),
("Mulher gato", "21", "0"),
("Mulher gato", "22", "0"),
("Mulher gato", "23", "0"),
("Mulher gato", "24", "0"),
("Mulher gato", "25", "0"),
("Mulher gato", "26", "0"),
("Mulher gato", "27", "0"),
("Mulher gato", "28", "0"),
("Mulher gato", "29", "0"),
("Mulher gato", "30", "0"),
("Mulher gato", "31", "0"),
("Mulher gato", "32", "0"),
("Mulher gato", "33", "0"),
("Mulher gato", "34", "0"),
("Mulher gato", "35", "0"),
("Mulher gato", "36", "0"),
("Mulher gato", "37", "0"),
("Mulher gato", "38", "0"),
("Mulher gato", "39", "0"),
("Mulher gato", "40", "0"),
("Mulher gato", "41", "0"),
("Outcast", "1", "0"),
("Outcast", "2", "0"),
("Outcast", "3", "0"),
("Outcast", "4", "0"),
("Outcast", "5", "0"),
("Outcast", "6", "0"),
("Outcast", "7", "0"),
("Outcast", "8", "0"),
("Outcast", "9", "0"),
("Outcast", "10", "0"),
("Outcast", "11", "0"),
("Outcast", "12", "0"),
("Outcast", "13", "0"),
("Outcast", "14", "0"),
("Outcast", "15", "0"),
("Outcast", "16", "0"),
("Outcast", "17", "0"),
("Outcast", "18", "0"),
("Outcast", "19", "0"),
("Outcast", "20", "0"),
("Outcast", "21", "0"),
("Outcast", "22", "0"),
("Outcast", "23", "0"),
("Outcast", "24", "0"),
("Outcast", "25", "0"),
("Lucifer", "1", "0"),
("Lucifer", "2", "0"),
("Lucifer", "3", "0"),
("Lucifer", "4", "0"),
("Lucifer", "5", "0"),
("Lucifer", "6", "0"),
("Lucifer", "7", "0"),
("Lucifer", "8", "0"),
("Lucifer", "9", "0"),
("Lucifer", "10", "0"),
("Lucifer", "11", "0"),
("Lucifer", "12", "0"),
("Lucifer", "13", "0"),
("Lucifer", "14", "0"),
("Lucifer", "15", "0"),
("Lucifer", "16", "0"),
("Lucifer", "17", "0"),
("Lucifer", "18", "0"),
("Lucifer", "19", "0"),
("Lucifer", "20", "0"),
("Lucifer", "21", "0"),
("Lucifer", "22", "0"),
("Lucifer", "23", "0"),
("Lucifer", "24", "0"),
("Lucifer", "25", "0"),
("Lucifer", "26", "0"),
("Lucifer", "27", "0"),
("Lucifer", "28", "0"),
("Lucifer", "29", "0"),
("Lucifer", "30", "0"),
("Lucifer", "31", "0"),
("Lucifer", "32", "0"),
("Lucifer", "33", "0"),
("Lucifer", "34", "0"),
("Lucifer", "35", "0"),
("Lucifer", "36", "0"),
("Lucifer", "37", "0"),
("Lucifer", "38", "0"),
("Lucifer", "39", "0"),
("Lucifer", "40", "0"),
("Lucifer", "41", "0"),
("Lucifer", "42", "0"),
("Lucifer", "43", "0"),
("Lucifer", "44", "0"),
("Lucifer", "45", "0"),
("Lucifer", "46", "0"),
("Lucifer", "47", "0"),
("Lucifer", "48", "0"),
("Lucifer", "49", "0"),
("Lucifer", "50", "0"),
("Besouro Azul", "1", "0"),
("Besouro Azul", "2", "0"),
("Besouro Azul", "3", "0"),
("Besouro Azul", "4", "0"),
("Besouro Azul", "5", "0"),
("Besouro Azul", "6", "0"),
("Besouro Azul", "7", "0"),
("Besouro Azul", "8", "0"),
("Besouro Azul", "9", "0"),
("Besouro Azul", "10", "0"),
("Trindade Anual", "1", "0"),
("Trindade", "1", "0"),
("Trindade", "2", "0"),
("Trindade", "3", "0"),
("Trindade", "4", "0"),
("Trindade", "5", "0"),
("Trindade", "6", "0"),
("Trindade", "7", "0"),
("Trindade", "8", "0"),
("Trindade", "9", "0"),
("Trindade", "10", "0"),
("Trindade", "11", "0"),
("Trindade", "12", "0"),
("Trindade", "13", "0");
insert into hqs
(titulo, edição, lido)
values
("A Espada de Azrael", "1", "1"),
("O Coringa", "1", "1"),
("the walking dead", "1", "1"),
("the walking dead", "2", "1"),
("the walking dead", "3", "1"),
("the walking dead", "4", "1"),
("the walking dead", "5", "1"),
("Dcesso", "1", "1"),
("Dcesso", "2", "1"),
("Dcesso", "3", "1"),
("Dcesso", "4", "1"),
("Dcesso", "5", "1"),
("Dcesso", "6", "1"),
("A noite mais densa", "1", "1"),
("A noite mais densa", "2", "1"),
("A noite mais densa", "3", "1"),
("A noite mais densa", "4", "1"),
("A noite mais densa", "5", "1"),
("A noite mais densa", "6", "1"),
("A noite mais densa", "7", "1"),
("A noite mais densa", "8", "1"),
("Universo DC", "00", "1"),
("Liga da Justiça Torre de Babel", "1", "1"),
("Exterminador", "1", "1"),
("Exterminador", "2", "1"),
("Lanternas Vermelhos", "1", "1"),
("Lanternas Vermelhos", "2", "1"),
("Lanternas Vermelhos", "3", "1"),
("Lanternas Vermelhos", "4", "1"),
("Lanternas Vermelhos", "5", "1"),
("Lanternas Vermelhos", "6", "1"),
("Lanternas Vermelhos", "7", "1"),
("Lanternas Vermelhos", "8", "1"),
("Lanternas Vermelhos", "9", "1"),
("Lanternas Vermelhos", "10", "1"),
("Lanternas Vermelhos", "11", "1"),
("Lanternas Vermelhos", "12", "1"),
("Lanternas Vermelhos", "13", "1"),
("Lanternas Vermelhos", "14", "1"),
("Lanternas Vermelhos", "15", "1"),
("Lanternas Vermelhos", "16", "1"),
("Lanternas Vermelhos", "17", "1"),
("Lanternas Vermelhos", "18", "1"),
("Lanternas Vermelhos", "19", "1"),
("Lanternas Vermelhos", "20", "1"),
("Lanternas Vermelhos", "21", "1"),
("Lanternas Vermelhos", "22", "1"),
("Lanternas Vermelhos", "23", "1"),
("Lanternas Vermelhos", "24", "1"),
("Lanternas Vermelhos", "25", "1"),
("Lanternas Vermelhos", "26", "1"),
("Lanternas Vermelhos", "27", "1"),
("Lanternas Vermelhos", "28", "1"),
("Lanternas Vermelhos", "29", "1"),
("Lanternas Vermelhos", "30", "1"),
("Lanternas Vermelhos", "31", "1"),
("Lanternas Vermelhos", "32", "1"),
("Lanternas Vermelhos", "33", "1"),
("Lanternas Vermelhos", "34", "1"),
("Lanternas Vermelhos", "35", "1"),
("Lanternas Vermelhos", "36", "1"),
("Lanternas Vermelhos", "37", "1"),
("Lanternas Vermelhos", "38", "1"),
("Lanternas Vermelhos", "39", "1"),
("Lanternas Vermelhos", "40", "1"),
("Batman vs Predador", "1", "1"),
("A Piada Mortal", "1", "1"),
("O Cavaleiro das trevas", "1", "1"),
("Três Coringas", "1", "1"),
("Três Coringas", "2", "1"),
("Três Coringas", "3", "1"),
("Watchmen", "1", "1"),
("A Origem de Galactus", "1", "1"),
("Adão Negro A Era Negra", "1", "1"),
("Adão Negro A Era Negra", "2", "1"),
("Adão Negro A Era Negra", "3", "1"),
("Adão Negro A Era Negra", "4", "1"),
("Adão Negro A Era Negra", "5", "1"),
("Adão Negro A Era Negra", "6", "1"),
("DC vs Marvel v1", "01", "1"),
("Batman", "401", "1"),
("Batman Ano zero", "1", "1"),
("Super filhos", "1", "1"),
("O Corvo", "1", "1"),
("Darth Vader v2", "1", "1"),
("ajax o cacador de marte (mini)", "1", "1"),
("ajax o cacador de marte (mini)", "2", "1"),
("O Botton", "1", "1"),
("O Botton", "2", "1"),
("O Botton", "3", "1"),
("O Botton", "4", "1"),
("Batman Amaldiçoado", "1", "1"),
("Liga da Justiça Elite", "1", "1"),
("Solomon Grundy", "1", "1"),
("Liga da Justiça", "1", "1"),
("Titas Renascem", "1", "1"),
("The Flash v3", "09", "1"),
("Especial de Natal 2009", "1", "1"),
("Lanternas Verdes Guerreiros Esmeralda", "1", "1"),
("Liga da justiça A guerra do demonio", "1", "1"); 
insert into Filmes
(titulo, diretor, Gênero, Ano)
values
("", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("", "", "", "");
drop database hqs;