create database músicas;
use músicas;

create table Música(
id_Música int not null auto_increment,
Cantor varchar(255),
Titulo varchar(255),
duração time,
primary key (id_Música)
);

insert into Música
(Cantor, Titulo, duração)
values
("Nissin, Fábio Brazza , Sant, Sid, Gog", "Brasil Colônia", "6:40"),
("Souto Mc", "Retorno", "2:43"),
("Souto Mc", "Caça e Caçadora", "2:56"),
("Coruja Bc1, Akira Presidente, Black, Rod 3030, Don L", "Lei Rua Neles", "8:00"),
("Atentado Napalm, Coruja BC1, Rincon Sapiência, Xamã, Sant, Rashid", "The Cypher Respect Vol. 2", "7:50"),
("Emicida, Drik Barbosa, Amiri, Rico Dalasam, Muzzike, Raphão Alaafin", "Mandume", "8:47"),
("Emicida, Majur e Pabllo Vittar", "AmarElo", "8:53"),
("Emicida", "Inácio da Catingueira", "4:01"),
("Criolo", "Boca de Lobo", "3:47"),
("MV Bill, Dj Caique", "Insalubre", "4:04"),
("Ogi, Bob, Rod3030, Rashid, Mc Cabelinho, L7NNON, Kayuá, Azzy, DK47, Mv Bill", "POETAS NO TOPO 3.3", "19:25"),
("Mv Bill, Knust, Dudu, Chris, Souto Mc, Gali, Black, Projota, Cesar Mc, Kamau", "POETAS NO TOPO 3.3", "19:24"),
("Mc Sid", "Brasil de Quem ? Parte 1", "2:57"),
("Mc Sid", "Brasil de Quem ? Parte 2", "4:11"),
("Mc Sid", "Brasil de Quem ? Parte 3", "4:36"),
("Mc Sid", "Brasil de Quem ? Parte 4", "3:15"),
("Mc Sid", "Cuidado Com O Que Deseja", "4:01"),
("Mc Sid", "Autobiografia parte 1", "3:14"),
("Mc Sid", "Autobiografia parte 2", "4:45"),
("Mc Sid", "Autobiografia parte 3", "5:30"),
("Mc Sid", "Assalto a Mão Letrada", "2:08"),
("Mc Sid", "Assalto a Mão Letrada 2", "4:04"),
("Cesar Mc", "Quem tem boca vaia Roma ", "3:24"),
("Cesar Mc, Crystal", "Canção Infantil", "7:04"),
("Cesar Mc", "Minha Última Letra", "5:10"),
("Projota", "Senhor Presidente", "3:36"),
("Projota", "Rebeldia", "3:46"),
("Projota, Negra Li", "O Homem que não tinha nada", "3:57"),
("Projota", "Muleque de Vila", "4:44"),
("Projota", "Oh Meu Deus", "3:04"),
("Projota", "Canção Pro Tempo", "4:01"),
("Projota", "Mulher Feita", "3:19"),
("Racionais MC's", "Salve", "2:16"),
("Racionais MC's", "Fórmula Mágica da Paz", "10:40"),
("Racionais MC's", "Mágico de Oz", "7:38"),
("Racionais MC's", "Qual Mentira Vou Acreditar", "7:42"),
("Racionais MC's", "Diário De Um Detento", "7:32"),
("Racionais MC's", "Periferia é Periferia", "6:00"),
("Racionais MC's", "Interlúdio", "2:35"),
("Racionais MC's", "Rapaz Comum", "6:20"),
("Racionais MC's", "Tô Ouvindo Alguém Me Chamar", "11:14"),
("Racionais MC's", "Capítulo 4 Versículo 3", "8:09"),
("Racionais MC's", "Genesis", "0:22"),
("Racionais MC's", "Jorge Da Capadócia", "2:49"),
("MV Bill", "Quarentena", "3:00"),
("MV Bill", "Isolamento", "3:27"),
("MV Bill, Kmila CDD, Beni KTT, Rod 3030, Leal, e MC Natalhão", "Palavra Poderosa", "6:50"),
("MV Bill", "Insalubre", "4:04"),
("MV Bill", "BRADO RETUMBANTE", "4:52"),
("MV Bill", "Só Deus pode me julgar", "6:49"),
("Sabotage", "Mun-rá", "4:36"),
("Sabotage", "Um Bom Lugar", "5:06"),
("Sabotage", "Rap É Compromisso", "4:25"),
("Sabotage e DBS, Negra Li, Lakers, Instituto e Ganjaman", "Canão Foi Tão Bom", ""),
("Sabotage", "Respeito É Pra Quem Tem", "5:30"),
("Sabotage", "Na Zona Sul", "5:16"),
("Sabotage e Mano Brown", "Love Song A Maior Dor de Um Homem", "4:14"),
("Sabotage", "No Brooklin", "5:50"),
("Sabotage", "Cocaína", "4:59"),
("Sabotage", "País Da Fome", "4:00"),
("Sabotage e DJ Cia", "País da Fome Homens Animais", "6:08"),
("Sabotage e Chorão", "Cantando Pro Santo", "6:33"),
("Sabotage", "O Gatilho", "6:39"),
("Sabotage", "País da Fome Parte 2", "5:13");
SELECT SUM(duração) AS total FROM Música;
drop database músicas;